---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data
```{r dat, echo = TRUE}
#Load required libraries
library(data.table)
library(ggplot2)
#Load csv data
dat <- data.table(read.csv("~/Downloads/activity.csv"))
```


## What is mean total number of steps taken per day?
```{r totalsteps, echo = TRUE}
#Ignore missing values in the dataset, use tapply on "steps" and sort by date. 
totalSteps <- tapply(dat$steps, dat$date, FUN = sum, na.rm = TRUE)
#Plot histogram and qplot
qplot(totalSteps, binwidth=3, xlab = "Total Number of Steps Taken Each Day", main = "Figure 1") + 
  geom_histogram(colour = "blue", fill= "blue")
mean(totalSteps, na.rm = TRUE)
median(totalSteps, na.rm = TRUE)
```

1. Average number of steps per day = ***9354.23***.
2. Median number of steps per day = ***10,395***


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
